### ISSUE TITLE
Prototipo de baja fidelidad

### ISSUE THREAD

**Issue by DaniSalermi** [NataGalvez/SCL010-Burger-Queen#9]

**Comment by NataGalvez** [comment]
[Prototipo baja fidelidad (Sección Comandas).pdf](https://github.com/NataGalvez/SCL010-Burger-Queen/files/3616888/Prototipo.baja.fidelidad.Seccion.Comandas.pdf)

**Comment by NataGalvez** [comment]
[Prototipo baja fidelidad (Sección Comandas).pdf](https://github.com/NataGalvez/SCL010-Burger-Queen/files/3616891/Prototipo.baja.fidelidad.Seccion.Comandas.pdf)
